### ISSUE TITLE
Menu disappears

### ISSUE THREAD

**Issue by dutchplayers** [HumanTree92/esx_advancedvehicleshop#12]
Hello,

I still have the issue that the shop menu disappears if scrolling it. I can now only buy the first vehicle.

We do not have issues with esx_menu_default on other resources. esx_vehicleshop is working great.

I already tried using the default esx_menu_default, but no luck.

Any idea? My console does not give any information, but since this is the only resource with this problem i wanted to ask you.

**Comment by HumanTree92** [comment]
Menu disappears if scrolling??? 

There is no bugs with this on my end. I've tried to recreate your issue but would sure love a video or something on this. Here is what i have tried:

1. Mouse Wheel Scrolling - Nothing Happens
2. Arrow Keys - Works like normal

**Comment by dutchplayers** [comment]
I've been testing it on another server, and that was working. It's however a bad on my end. 

Not yet sure what.
