### ISSUE TITLE
No such export GeneratePlate

### ISSUE THREAD

**Issue by mrfuge** [HumanTree92/esx_advancedvehicleshop#13]
Hello, i am trying to buy police vehicles from the shop with policejob and advancedvehshop. I also have esx_vehicleshop installed. I removed the dependency in the fxmanifest, bu i get the following error when pressing yes to buy a vehicle:

SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:924: No such export GeneratePlate in resource esx_advancedvehicleshop

Any help?

**Comment by HumanTree92** [comment]
Are you using esx_policejobs vehicle shop or esx_advancedvehicleshop to buy police vehicles. If your using esx_policejob to buy vehicles then make sure you edit your esx_policejob>client>vehicle.lua as stated in the Readme
