### ISSUE TITLE
 Does not appear in-game

### ISSUE THREAD

**Issue by BerSeCk001** [HumanTree92/esx_advancedvehicleshop#14]
I have loaded this to the esx folder I have also put the start and the sql to the database and set to true inside config.lua but nothing appears within the game

**Comment by HumanTree92** [comment]
Send ur config.lua. Also check the console console for any errors.

**Comment by BerSeCk001** [comment]
any error in the console and this is the configuration of lua
https://discordapp.com/channels/@me/319474431082758144/709129790749278278

**Comment by BerSeCk001** [comment]
any error in the console and this is the configuration of lua
https://imgur.com/PdSwANX

**Comment by BerSeCk001** [comment]
I think I have found the problem. when i try to start esx advancedvehicleshops it needs esx licenseshop but licenseshop gives me these errors. How can I fix them?
https://imgur.com/S4DoLBT

**Comment by HumanTree92** [comment]
That error for licenseshop means u have an error. It will tell u what line the error is on

**Comment by BerSeCk001** [comment]
Exactly the error is from line 292 to line 318 but default is configured. I don't know what I have to change to fix it

**Comment by HumanTree92** [comment]
Fixed in https://github.com/HumanTree92/esx_licenseshop/commit/185a2c341a0334d9fe5c57ae58e1b4e3c48615e7
