### ISSUE TITLE
Menu disappears after using arrow keys

### ISSUE THREAD

**Issue by SlendE1** [HumanTree92/esx_advancedvehicleshop#15]
When I open up the vehicle shop, I can browse through maybe 1 or 2 cars before the menu disappears and leaves me frozen in a vehicle, this happens with all shops in advanved vehicle shop, esx_vehicleshop works fine, however as soon as I switch over to advanced I get the issue, there is no error in my logs/F8 menu, and yes I have uploaded the sql to my database. I have tried moving the blip and disabling potential conflicting resources but no luck.

**Comment by HumanTree92** [comment]
U didn't follow the readme. U have to remove esx_vehiclshop from esx_policejob and esx_ambulancejob. Also if u had looked through the closed commits u would have seen that this issue has been resolved

**Comment by SlendE1** [comment]
i did in fact follow the read me, all instances of esx_vehicleshop have been switched to advanced, dependencies removed, also i do not see this issue resolved in closed commits, would you be able to point out which one is the solution?

**Comment by HumanTree92** [comment]
Well there is roughly 3 closed issues where it was fixed. Are u using the latest es_extended?

**Comment by SlendE1** [comment]
version 1.2

**Comment by HumanTree92** [comment]
Try using the latest master.

**Comment by SlendE1** [comment]
fresh install of es_extended same issue, however i have discovered that everytime i move the "ShopInsideCar" zone i can view more vehicles before it kicks me out.

**Comment by SlendE1** [comment]
https://github.com/HumanTree92/esx_advancedvehicleshop/commit/136bc2457d78f1ee683a97f35c1864fde735bbed

after reversing the commit done above, I have fixed the issue.
