### ISSUE TITLE
UI Dissappears

### ISSUE THREAD

**Issue by PeakAlive** [HumanTree92/esx_advancedvehicleshop#18]
Hi,
I have read the readme and installed everything correctly,
But I am having an issue with the UI,
For the 1st vehicle there is no issue, but if you press your arrows to change vehicle the UI just dissapears and you are stuck on that screen.

I have read this is due to 500+ vehicles but I am using the default sql file, I haven't added a single vehicle to it.

Another issue I'm having is that whenever there's a showmodel, and the person buys a vehicle, the vehicle doesn't spawn untill you press F to enter the car, which spawns a new model.

Any help please?

PS: I also have this same exact issue using esx_vehicleshop

Thanks in advance

**Comment by HumanTree92** [comment]
If you are having the same issue using esx_vehicleshop then you have installed ESX wrong. Unless you have any errors that show up i can't help. Simply saying that the UI Disappears doesn't help me since i have no issues at all. So i would check to make sure you have installed all the Required ESX Resources including the 3 ESX Menus.

**Comment by PeakAlive** [comment]
I am 100% sure I installed ESX correctly, 
I do have the 3 ESX Menus and everything else like inventory, shops etc works perfectly fine, 
It's only with the vehicleshop that I'm having this issue for some reason, 
I've been looking at it for multiple weeks already and I can't seem to fix it...

**Comment by OuDayas** [comment]
wich version we have to use of esx?

**Comment by HumanTree92** [comment]
Well if your trying to use any Version above V1 Finale then RIP you. I have stated in all the Readmes to only use V1 Finals or ExtendedMode as V2 ditched every single esx_ resource. 

I would try setting this script to be the last esx_ resource and see if that works. Also for your server.cfg or resources.cfg are you using ensure or start? If your ensure trying changing everything to start except the default FiveM Scripts.

**Comment by HumanTree92** [comment]
If your using SESX then i won't help you. SESX is outdated by well over a year. So this script only supports ESX V1 Final or Extendedmode.

**Comment by HumanTree92** [comment]
When your not using SESX and your using the Lastest ESX Scripts then you can re-open this issue. SESX is a poorly built system.
