### ISSUE TITLE
Problem with notifications

### ISSUE THREAD

**Issue by TylerBrink1** [HumanTree92/esx_advancedvehicleshop#19]
Hi,
I have read the readme and installed everything correctly,
But I am having an issue with when i buy a vehicle i click on the vehicle then click yes and it takes the money but it dosent give any notification saying i bought the vehicle

Thats the error i get for all but that just the one from the car shop. Could i get some help please.

![](https://cdn.discordapp.com/attachments/695696627196756040/718594836411711558/2020-06-06_2.png)

**Comment by TylerBrink1** [comment]
@HumanTree92 Please help?

**Comment by HumanTree92** [comment]
Update your es_extended to V1 Final or use ExtendedMode Master
