### ISSUE TITLE
Reselling car not working as expected

### ISSUE THREAD

**Issue by mesl** [HumanTree92/esx_advancedvehicleshop#2]
Hello, When I try to resell a car bought at the vehicle/car shop nothing pops up,
I have found an issue where with every other sell point an error pops up in the F8 console and that also doesn't pop up, so I suspect it doesn't check for a vehicle

This is a picture of the console error I get when driving on top of other selling points without the right vehicle
(If I try to drive over the right selling point with a car, nothing pops up)

![image](https://user-images.githubusercontent.com/10009454/75057532-87ba6e80-54d9-11ea-9377-66280cdf7bc2.png)

Thank you!
Kind regards, Mesl

**Comment by HumanTree92** [comment]
This should be fixed in 7f3ba33fbb278b9dea372ea98c5947d2d01684a4
