### ISSUE TITLE
Disable keys 

### ISSUE THREAD

**Issue by Timmyopp** [HumanTree92/esx_advancedvehicleshop#20]
How can I disable keys so people won't be able to drive the car while watching it on shop menu?

**Comment by HumanTree92** [comment]
hmm thats weird b/c you shouldn't be able to drive the vehicle as it has FreezeEntityPosition. You can try editing the function at line 209 and do DisableControlAction with whatever keys you want. You can find the Key List on the [FiveM Docs Page](https://docs.fivem.net/docs/)
