### ISSUE TITLE
2 Errors

### ISSUE THREAD

**Issue by LlamaPalooza89** [HumanTree92/esx_advancedvehicleshop#21]
1 advancedvehicleshop - boat "" does not exist????
script error for client/main.lua line 868........

**Comment by HumanTree92** [comment]
Did you import the sql. Plus you say script error for client/main.lua line 868 which is `table.insert(vehiclesByCategory[VehiclesC[i].category], VehiclesC[i])`

But that has to do with getting the Categories. So you have made a mistake somewhere in your DB
