### ISSUE TITLE
The menu disappears

### ISSUE THREAD

**Issue by BuddiesTV** [HumanTree92/esx_advancedvehicleshop#22]
Hey iam using v1 final of es_extendet and esx_vehicleshop was working but esx_advancedvehicleshop not, when i go an car down or up the menu disappears with no error or something.

**Comment by HumanTree92** [comment]
R u sure that you are using the latest of this script. I have fixed this issue https://github.com/HumanTree92/esx_advancedvehicleshop/commit/7080b126d41dc2d7ab7c7d00aa7335689363aaca

**Comment by BuddiesTV** [comment]
Yes, sure its the Lates version

**Comment by HumanTree92** [comment]
Ok so few questions:
1. R u positive that you have imported the SQL for this script.
2. R u using SESX?
3. Is there any way you can send me a small video of what is going on?

**Comment by Minddead** [comment]
**esx_vehicleshop with advancedvehicleshop running:** in your shop, the carshop is false
https://streamable.com/25716j
**Vehicleshop without advancedvehicleshop running:**
https://streamable.com/fsk8tl

when i use only advancedvehicleshop with carshop = true  the same is happening

Truck,Aircraft and Boatshop working without any problem. 
I use a second vehicleshop as ImportVehicleshop this shop is working too without any problems.

I insert only the the Truck,Boat, Aircraft and Cardealershop Items into the Databank. Never use the other shops like Ambulance,Police,...

**Comment by HumanTree92** [comment]
Don't use this script and esx_vehicleshop at the same time. Make sure u also make the changes to both esx_policejob and esx_ambulancejob.

**Comment by akbaig** [comment]
I just had the same issue as @BuddiesTV 

I fixed it by removing the dependency of _esx_vehicleshop_ in **esx_advancedgarage**

@HumanTree92 You might want to remove that dependency causing the resource to start automatically.

Peace

**Comment by HumanTree92** [comment]
> 
> 
> I just had the same issue as @BuddiesTV
> 
> I fixed it by removing the dependency of _esx_vehicleshop_ in **esx_advancedgarage**
> 
> @HumanTree92 You might want to remove that dependency causing the resource to start automatically.
> 
> Peace

esx_advancedgarage doesn't have the Dependency for esx_vehicleshop. It has it as an Optional Requirement just like esx_advancedvehicleshop. However you have to make sure you remove the Dependency for esx_policejob & esx_ambulancejob. As well as any other script that requests esx_vehicleshop. All of that is noted in the Wiki & the Readme.

**Comment by HumanTree92** [comment]
Re-open if the issues continues
