### ISSUE TITLE
Rank inheritance not working correctly

### ISSUE THREAD

**Issue by JackW6809** [HumanTree92/esx_advancedvehicleshop#24]
**Describe the Bug | A Clear & Concise Description of Bug**
I have created two departments. LAPD/LACSD and CHP. LAPD uses the normal police label. Whereas CHP uses its own chp tag, For some reason when I set my rank to the boss in CHP it cannot access the vehicles below it. It can access the vehicles I put into its own rank but that's it. E.g. I am the Commissioner rank and try to access the cadet cars. Gives me: This vehicle is not for your rank! I do not mind that LAPD/LACSD can access CHP cars as it is no biggy. Just kind of annoying that I cannot access vehicles below the top rank.

**Questions**
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: No Wiki for it
What Version of es_extended are you using?: V1 Final (https://github.com/esx-framework/es_extended/releases/tag/v1-final)
Are you using a Pre-Installed ESX?: No
Are you using Essentialmode?: No
Are you using OneSync?: No
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
So say for instance you have 3 Police Ranks. Lets say Cadet, Police Officer, & Boss. In order for the boss to get access to both Cadet & Police Officer vehicles you have to duplicate them like in the sql. So for instance if you have a vehicle called police7 and you have it for Police Officer in order to give it to the Boss Rank as well you must duplicate it and change the category to the boss rank.

**Comment by JackW6809** [comment]
Hmm, okay. Thank you for that. Is there not a way to get around that because if you have lots of police vehicles it can become a tedious task?

**Comment by HumanTree92** [comment]
No sadly not. I did it that way b/c it was the only way. Plus for my server the higher the rank the more discounts on vehicles people get. But in all honestly you shouldn't have more then 10 Total Police Vehicles.

**Comment by JackW6809** [comment]
Okay, no problem. Do you ever plan on adding more customization for like adding multiple departments?

**Comment by HumanTree92** [comment]
The script is easily customizable to add more things.
