### ISSUE TITLE
esx_advancedvehicleshop error no cars found, no trucks found etc

### ISSUE THREAD

**Issue by sonicbroadcasting** [HumanTree92/esx_advancedvehicleshop#26]
**Describe the Bug | A Clear & Concise Description of Bug**

Added into resource file, start in config, shows on map, but wont except the sql because of previous vehicle sql. deleted vehicle shop completely from resources and removed from server.cfg. left in advancedvehicle shop. deleted all vehicles out of vs_cars list in sql and tried to enter in one manually as a test. still no vehicles found. using esx, zap-hosting myphp. Linux with essential mode.
**Questions**
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: 
What Version of es_extended are you using?: 
Are you using a Pre-Installed ESX?: 
Are you using Essentialmode?: 
Are you using OneSync?: 
Linux or Windows?:

**Comment by HumanTree92** [comment]
Please answer my questions

**Comment by sonicbroadcasting** [comment]
checked closed topics
checked wiki but dont know where to find fxmanifest.lua 
newest version of es_extended its and essential mode pack on zap-hosting
yes pre installed esx i guess
yes have essential mode. its included in the pack for es_extended
no using filezilla with zap hosting
Runing on linux

**Comment by sonicbroadcasting** [comment]
if it is the vmenu fxmanifest.lua already change it all to esx_advancedvehicleshop

**Comment by sonicbroadcasting** [comment]
so just put it back in and it works but gives off same errot as before

 SCRIPT ERROR: @ ESX_ADVANCEDVEHICLESHOP/CLIENT/MAIN.LUA:978: ATTEMPT TO INDEX A NIL VALUE (LOCAL "FIRSTVEHICLEDATE")
>HANDLER (@ES_EXTENDED/CLIENT/FUNCTIONS.LUA:1316)


LINE 978

	DeleteDisplayVehicleInsideShop()
	WaitForVehicleToLoad(firstVehicleData.model)

	ESX.Game.SpawnLocalVehicle(firstVehicleData.model, Config.Zones.ShopInsideCar.Pos, Config.Zones.ShopInsideCar.Heading, function(vehicle)
		currentDisplayVehicle = vehicle
		TaskWarpPedIntoVehicle(playerPed, vehicle, -1)
		FreezeEntityPosition(vehicle, true)
		SetModelAsNoLongerNeeded(firstVehicleData.model)
	end)
end

**Comment by sonicbroadcasting** [comment]
if i add in advanced license then i lose the vehicles all together and it says there isnt any

**Comment by HumanTree92** [comment]
I had a similar person tell me the exact thing about using Zap Hostings Pre-Installed ESX. The problem is well the Zap Hosting ESX

Most if not all of Zaps scripts are out of date. All my scripts are updated to support ESX V1 Final or EXM Latest. I recommend downloading the scripts yourself & installing them. The only pre-installed ESX i can recommend is Ribsosay as its the only pre-installed ESX that stays up to date. But Ribsosay is a Paid pre-install of ESX.

**Comment by sonicbroadcasting** [comment]
everything is set on an auto update through their website. 
![0_20200720151540_1](https://user-images.githubusercontent.com/68518371/87977006-feb15e80-ca9b-11ea-9085-be488a0f14b3.png)

**Comment by sonicbroadcasting** [comment]
this is the error after restarting the server.

**Comment by sonicbroadcasting** [comment]
I really like your script and just wanna figure out how to resolve this so i can have it in the server. have problems with the advanced license and advanced weapon shop as well. only issues is i am new to all of this and learning. i dont know where to begin in replacing my esx with v1 and

**Comment by sonicbroadcasting** [comment]
ok i see. so esx v1 final is the old version. im running on the new one.

**Comment by HumanTree92** [comment]
You have to wait a few mins when accessing the script as there is a lot to load. Thats why it says No Cars found. You also have to make sure you have uploaded my sql file. But as i said before Zap Hosting doesn't use update versions of scripts. So the chances of being able to use any of my scripts or custom scripts that work for V1 is very unlikely

**Comment by HumanTree92** [comment]
Now if your using Zap Hostings ESX which are located here https://github.com/zap-fivem/esx they are not the newest ESX which is V2. ESX V2 doesn't support any esx_ resource. You would know b/c there would be tons of errors when you try to use a script like esx_skin.

**Comment by HumanTree92** [comment]
To better help you understanding. [This is ESX made by Zap](https://github.com/zap-fivem/esx/tree/master/es_extended) | [This is ESX V1 Final made by ESX Framework](https://github.com/esx-framework/es_extended/tree/v1-final) | [This is ESX V2 made by ESX Framework](https://github.com/esx-framework/es_extended/tree/develop). ESX Made by Zap should be a Huge no no as most scripts have had major updates & improvements that you are missing out on. ESX V2 will be great once it is finished. ESX V1 Final is what you should be using if you want this script to work.

So all in all if you want to use my scripts use ESX V1 Final or ExtendedMode

**Comment by sonicbroadcasting** [comment]
ok. i dragged in the es_extended from v1 final to filezilla and server wont start. so no clue 
![0_20200720153822_1](https://user-images.githubusercontent.com/68518371/87979039-6ddc8200-ca9f-11ea-8695-fb9fe85d73ad.png)

**Comment by HumanTree92** [comment]
That means you have installed it incorrectly. Your best bet will be to restart. Download all your files from github and upload them. It will be very time consuming. But its the best way to make sure all scripts are updated & working. I won't help you install ESX. If you would like help join the ESX Discord at https://discord.me/esx

**Comment by sonicbroadcasting** [comment]
right on. yeah just really like the script. ill get it figured out appreciate the info

**Comment by HumanTree92** [comment]
Not a problem. Just remember if you need help installing ESX Scripts you can ask on the ESX Forums at https://forum.esx-framework.org/
