### ISSUE TITLE
esx_advanvedvehicleshop/client/main.lua:248:

### ISSUE THREAD

**Issue by YInfeRnal** [HumanTree92/esx_advancedvehicleshop#27]
**Describe the Bug | A Clear & Concise Description of Bug**
when i enter ambulance shop to buy vehicle in ambulance i got that error
esx_advanvedvehicleshop/client/main.lua:248: please ?

**Questions**
Have you looked through the Closed Topics?: y
Have you looked through the Wiki?: y
What Version of es_extended are you using?: exm
Are you using a Pre-Installed ESX?: no
Are you using Essentialmode?: y
Are you using OneSync?: y
Linux or Windows?: w

**Comment by HumanTree92** [comment]
Did you edit the sql?

**Comment by HumanTree92** [comment]
Whats the full error if you have it?

**Comment by YInfeRnal** [comment]
thats the error : https://imgur.com/a/Om9MMEy

**Comment by YInfeRnal** [comment]
thats my sql : https://imgur.com/a/fScqNSm

**Comment by YInfeRnal** [comment]
and : https://imgur.com/a/AOufGu8

**Comment by YInfeRnal** [comment]
whats wrong?

**Comment by YInfeRnal** [comment]
police shop fix

**Comment by HumanTree92** [comment]
It could be many thins. 
1. For instance it could be your advancedparamedic is too long of a category name. Try shortening the names of your categories. You can leave the labels. 
2. A vehicle model can't be found.

**Comment by YInfeRnal** [comment]
a vehicle model is fine but i try 1 now

**Comment by HumanTree92** [comment]
It seems you are also missing the category for paramedic3

**Comment by YInfeRnal** [comment]
i dont have paramedic 3 grade :small

**Comment by HumanTree92** [comment]
Well look at this image https://imgur.com/a/AOufGu8

**Comment by HumanTree92** [comment]
ID 18, 19, & 20 for the category say paramedic3

**Comment by YInfeRnal** [comment]
shht thats my fail
i dont have paramedic3 :D :D but i add it here :D
wait i fix it

**Comment by HumanTree92** [comment]
Also what is the point in having all those grades if they have access to the same vehicles. Honestly its a cluster fuck.

**Comment by YInfeRnal** [comment]
Salary? :D
i removed paramedic3 still not working...
i cut advanced paramedic but sitll not work

**Comment by YInfeRnal** [comment]
:(:(:(:(

**Comment by YInfeRnal** [comment]
thats my ambulance grade

**Comment by YInfeRnal** [comment]
https://imgur.com/a/vJTd1C0

**Comment by HumanTree92** [comment]
So you removed ID 18, 19, & 20 from vs_ambulance_categories

**Comment by YInfeRnal** [comment]
this all my tables : https://imgur.com/a/u7holIV

**Comment by YInfeRnal** [comment]
for the policejob is fixes and have no problem but when i setjob to ambulance and go to ambulance shop error happen and game frezzed you need to do freeze unfreeze 
can you do with anydesk maybe?

**Comment by YInfeRnal** [comment]
whats wrong you think?

**Comment by HumanTree92** [comment]
So you don't have any problems with the police one. Whats your grades & categories look like for police

**Comment by YInfeRnal** [comment]
no i dont have any problem with police one

**Comment by HumanTree92** [comment]
Can you send pictures of your police stuff

**Comment by YInfeRnal** [comment]
yes wait

**Comment by YInfeRnal** [comment]
![bandicam 2020-07-26 01-19-04-811](https://user-images.githubusercontent.com/65487734/88466093-3a09be00-cede-11ea-94d1-21fab2526593.jpg)
![bandicam 2020-07-26 01-19-58-178](https://user-images.githubusercontent.com/65487734/88466096-3c6c1800-cede-11ea-9399-87d803f43c30.jpg)
![bandicam 2020-07-26 01-20-25-477](https://user-images.githubusercontent.com/65487734/88466097-3d9d4500-cede-11ea-86dc-c5e12939a77a.jpg)


![bandicam 2020-07-26 01-19-52-247](https://user-images.githubusercontent.com/65487734/88466094-3bd38180-cede-11ea-8d23-1a73a324d41b.jpg)

**Comment by YInfeRnal** [comment]
thats my police work with no any problem

**Comment by HumanTree92** [comment]
Can you export & send me the files for vs_ambulance, vs_ambulance_categories, & job_grades

**Comment by YInfeRnal** [comment]
yes wait

**Comment by YInfeRnal** [comment]
https://filebin.net/7koco6yeg2zni3he

**Comment by YInfeRnal** [comment]
thats the video from what happen
https://filebin.net/jofgwhwgesdjc2ru

**Comment by HumanTree92** [comment]
So when i downloaded those files for me it shows this:
1. For vs_ambulance - (3, 'Ambulance 1', 'lsambulance', 200, 'emt1\r\n'),
2. For vs_ambulance_categories - ('emt1\r\n', 'EMT 1'),

**Comment by YInfeRnal** [comment]
wtf why this happen in the phpmyadmin its fixed !
wait i try that

**Comment by YInfeRnal** [comment]
the problem is fixed
why in phpmyadmin its not like this ahh
bro thanks you this is not your scrip problem but you help me to fix my problem thanks for your help

**Comment by HumanTree92** [comment]
Not a problem.

**Comment by HumanTree92** [comment]
Also that many grades just for salary is kinda dumb. Honestly if your setting this up for a Private server then it would be fine but if your trying to setup a Public Server good luck as it doesn't look that great. If i was you i would re-write your grades & Categories. (This is the best option as for me my grades are like [this](https://www.firetactics.com/firefighter-ranks/)) for Fire/Rescue. You should probably do the same thing for your Police. Its just looks better to have actual ranks.
