### ISSUE TITLE
big problem without any error! for someones not all players...

### ISSUE THREAD

**Issue by fucekar** [HumanTree92/esx_advancedvehicleshop#29]
**Describe the Bug | A Clear & Concise Description of Bug**
this for someone happen and after sv restart or.. not fixed and someones cannot do anything...
but just for someone and some players dont have this issue i dont know why this problem just for someones 
when you buy a vehicle in police or ambulance shop you go to the police cars and you purchage easy with no problem / but !
when you buy the car buyed fine and spawn but you dont :| only car spawn and you freeze and invisible :|
in the car store when you buy car you invisible and freeze but you buy car and your car purcchaged and spawned but you dont..
how to fix? thanks thats big problem.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: n
Have you looked through the Closed Topics?: y
Have you looked through the Wiki?: y
Are you using a Pre-Installed ESX? If Yes who?: n
Are you using es_extended? If Yes what Version? (Example: 1.2): n
Are you using Essentialmode?: y
Are you using ExtendedMode?: y
Are you using OneSync?: y
Linux or Windows?: w

**Comment by HumanTree92** [comment]
I don't understand your problem. Your English is too poor for me to understand.

**Comment by fucekar** [comment]
ok i will send video

**Comment by fucekar** [comment]
![image](https://user-images.githubusercontent.com/69375242/90099654-38e6e680-dd50-11ea-9ab8-813a50fabfb4.png)
this should be here i install esx_advancedvehicleshop 1 more time( reinstall) and after that ambulance and police shop not work for me :| esx_advancedgarage good and when i active UseAmbulanceBlip to true i see blip to !
but for UseAmbulanceShop to true i dont see anything

**Comment by fucekar** [comment]
without any error in f8 or console

**Comment by fucekar** [comment]
i mean any blips for menu or.. not here... to purchage car just for jobs

**Comment by HumanTree92** [comment]
Make sure your job is set to that job
