### ISSUE TITLE
F8 error

### ISSUE THREAD

**Issue by Racpy** [HumanTree92/esx_advancedvehicleshop#3]
joining server then i go to car vehicleshop press E , will get this error , 
restart sciprt will fix , after restart when other player joining will get it too

SCRIPT ERROR: @esx_advancedvehicleshop/client/main.lua:548:
bad argument #1 to 'insert' (table expected, got nil)

**Comment by HumanTree92** [comment]
Should be fixed in 8663701e8df421faf2349eb774038e7821631c7d if not let me know.

**Comment by Racpy** [comment]
fixed
