### ISSUE TITLE
VIP shop not showing anything

### ISSUE THREAD

**Issue by Arsalan0098** [HumanTree92/esx_advancedvehicleshop#30]
eveything works fine but my VIP shop dont show any vehicle
there is car in database also in console it show no error or anything
**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  nope
Have you looked through the Closed Topics?:  yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?:  nope
Are you using es_extended? If Yes what Version? (Example: 1.2):  1.2
Are you using Essentialmode?:  no
Are you using ExtendedMode?:  no
Are you using OneSync?: yes
Linux or Windows?:  windows

**Comment by HumanTree92** [comment]
Do you have a VIP script setup. If so you also have to implement it yourself into the script. The VIP shop should only be used for those who know how to edit code

**Comment by Arsalan0098** [comment]
do you mind give me a little more hint? or advice me some vip script? i add custom feild for users to add some special coins so if they have enough coins they can buy from vip shop, thats what i want to do, and it would be awsome if you give me more hints
Thank you for your great release btw

**Comment by HumanTree92** [comment]
I have mine tied up with a field in my DB. It just checks to see if the field is true or false. If true then they are allowed to open the shop menu.

**Comment by Arsalan0098** [comment]
thanks for the hint, i just use some mysql fetch lines to get the coins and then make the garage working with my coins :p thanks for scripts man

**Comment by HumanTree92** [comment]
You could have the coins saved in the users table. In a Separate field. Example: if player has 500 Coins then grant access to shop. If a purchase is made during the shop remove x amount of Coins. 

There is a few ways of doing it. I just have mine setup so if someone donates the get access to the VIP shop so long as they keep donating each month. If they cancel their subscription they lose access to the shop but they can still drive their VIP Vehicles. And they can sell them if they want. I have my VIP system tied with my custom scripts that are tied to my server. Thats why i didn't release my VIP system.

**Comment by Arsalan0098** [comment]
yeah i understand, i just create a new table with identity and Coins to make it simple if they buy coin from my site it will add to the database automaticly and then everyone have access to see the VIP shop but no one can not buy until they have money in the database 👍 
just one other question which is not related to your script but it would be great if you can help cuz i search alot and did not find anything, i see in one server that there was some car model (mock) in the shop so players can get in the car but it will not move or something, and the car is there all the time, im sorry for my bad english i hope you understand me, is there a way to make something like that? or did you see any script like that?
thanks

**Comment by HumanTree92** [comment]
I would take a look at [this script](https://forum.cfx.re/t/release-esx-qalle-sellvehicles-sell-used-cars/196642) you can use some code from it. I plan on implementing a feature like this in the future. 

Or you could try something like this using [this](https://runtime.fivem.net/doc/natives/?_0xAF35D0D2583051B0)
```
Citizen.CreateThread(function()
    if Config.EnableDisplays then
		RequestModel(GetHashKey("adder"))

		while not HasModelLoaded(GetHashKey("adder")) do
			Wait(1)
		end

		for k,v in pairs(Config.Displays) do
			local veh = CreateVehicle(0xB779A091, v.Coords, v.Heading, false, true)

			SetEntityHeading(veh, v.Heading)
			FreezeEntityPosition(veh, true)
			SetEntityInvincible(veh, true)
			SetBlockingOfNonTemporaryEvents(veh, true)
		end
	end
end)
```

I'm not sure if the above code works or not. I haven't tested it but it should work so long as you do a config.lua & have 
```
Config.EnableDisplays = true
Config.Displays = {
	LS_CarShop = {Coords = vector3(VALUE_X, VALUE_Y, VALUE_Z), Heading = HEADING_HERE},
}
```

**Comment by Arsalan0098** [comment]
Thanks alot man, it works fine.

**Comment by ivancio** [comment]
I know something about lua, if you could please give me a hint of which script to use VIP to show the VIP vehicles of the store, I would appreciate it and I tried many scripts and this is the best in terms of store and garage my congratulations

**Comment by HumanTree92** [comment]
I use a Custom Discord Ace Perms that checks if a player is VIP. If that player is VIP then it tells the server that they are VIP & sets a value in the users table that they are VIP.

**Comment by Arsalan0098** [comment]
> I know something about lua, if you could please give me a hint of which script to use VIP to show the VIP vehicles of the store, I would appreciate it and I tried many scripts and this is the best in terms of store and garage my congratulations

i use my own payment system which is not gonno work on your server :-( sorry
