### ISSUE TITLE
bad argument #1 to 'insert' (table expected, got nil)

### ISSUE THREAD

**Issue by Hurstzy** [HumanTree92/esx_advancedvehicleshop#32]
**Describe the Bug | A Clear & Concise Description of Bug**
`esx_advancedvehicleshop/client/main.lua:1664: bad argument #1 to 'insert' (table expected, got nil)` I get this after putting cars into the DB in the VIP shop.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: I added the ace perm check for the VIP. 
Have you looked through the Closed Topics?:  Yes.
Have you looked through the Wiki?: Yes.
Are you using a Pre-Installed ESX? If Yes who?: No.
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.1
Are you using Essentialmode?: No
Are you using ExtendedMode?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Can you post a zip of the files that you are using.

**Comment by Hurstzy** [comment]
`esx_advancedvehicleshop/client/main.lua:1666: bad argument #1 to 'insert' (table expected, got nil)` there is the error and here is the zip
[esx_advancedvehicleshop.zip](https://github.com/HumanTree92/esx_advancedvehicleshop/files/5177568/esx_advancedvehicleshop.zip)

**Comment by HumanTree92** [comment]
So when i downloaded the zip i can see a few problems with the sql. 

1. vs_vip_categories has all these extra Categories that are not being used. Not a huge problem tho
2. vs_vips has this `('Shotaro','shotaro',30000,'motorcycles')` but the category for motorcycles isn't there. As you have it set as `('motos','Motorcycles'),` when it should be `('motorcycles','Motorcycles'),` or you could use `('motos','Motorcycles'),` but then the bike must be like this `('Shotaro','shotaro',30000,'motos')`

Sorry for the long waited reply. Got married on the day you commented.
