### ISSUE TITLE
So So Big Problem Sometimes Happen On Players...

### ISSUE THREAD

**Issue by fucekar** [HumanTree92/esx_advancedvehicleshop#33]
**Describe the Bug | A Clear & Concise Description of Bug**
so i made a video for show you

https://gofile.io/d/W880Zk
https://gofile.io/d/W880Zk

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): i dont use esx
Are you using Essentialmode?: for now yes
Are you using ExtendedMode?: yes
Are you using OneSync?: yes
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Any errors? Like on the Clientside or Serverside?

**Comment by fucekar** [comment]
nothing
just for someones
sometimes
this happen
no any error from anything or anywhere

**Comment by HumanTree92** [comment]
So it only happens when someone purchases a vehicle.

**Comment by fucekar** [comment]
thats 100% right and just for job shop
like policejob and ambulancejob shops

**Comment by HumanTree92** [comment]
Is this problem still happening. If so can you tell me what it was again. The videos are not there anymore.
