### ISSUE TITLE
BUG - Purchases (2x [Enter] mess up)

### ISSUE THREAD

**Issue by XvenDeR** [HumanTree92/esx_advancedvehicleshop#35]
**BUG OF MULTIPLE PURCHASE OF AN VEHICLE**
I went to vehicles shop, accidentally pressed [Enter] two times and 2 vehicles were purchased.

![image](https://user-images.githubusercontent.com/29688478/97088444-8c6f8d80-1639-11eb-8803-b20b7284c416.png)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: **NO.**
Have you looked through the Closed Topics?: **NO.**
Have you looked through the Wiki?: **NO.**
Are you using a Pre-Installed ESX? If Yes who?: **NO.**
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.0
Are you using Essentialmode?: **YES.**
Are you using ExtendedMode?: **NO.**
Are you using OneSync?: **YES.**
Linux or Windows?: **Windows.**

**Comment by HumanTree92** [comment]
Have you found a fix for this. I have been testing many different methods but still no fix.

**Comment by XvenDeR** [comment]
Sorry, haven't looked in to it

**Comment by HumanTree92** [comment]
Fixed in https://github.com/HumanTree92/esx_advancedvehicleshop/commit/084c23002ef1d79118e49bfdb4488a0f9c73ccf9
