### ISSUE TITLE
Error with VIP Shop, dont show vehicles

### ISSUE THREAD

**Issue by ChristianTorresGonzalez** [HumanTree92/esx_advancedvehicleshop#36]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): Yes
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: I dont know
Linux or Windows?: Windows

My problem is that i have vehicles in the vs_vips, and in categories, but in the server, when i try to open the meny, i have this error "[esx_advancedvehicleshio] [ERROR] No VIP Vehicles Found !!!"

**Comment by HumanTree92** [comment]
Few things to try:
1. Send me a picture of you vs_vips & vs_vip_categories
2. When restarting the script make sure you give it time to load everything. Each time you restart the script it has to load every single shop. So waiting 2-5mins is best when you restart the script.

**Comment by HumanTree92** [comment]
Re-Open issue when you comment.
