### ISSUE TITLE
Script Error with vehicle category

### ISSUE THREAD

**Issue by ChrisC1434** [HumanTree92/esx_advancedvehicleshop#37]
**Describe the Bug | A Clear & Concise Description of Bug**
I added in-vehicle categories for add-on vehicles, Now when I go to use the purchase circle it turns me invisible and no menu shows up and I get this error.-  SCRIPT ERROR: @esx_advancedvehicleshop/client/main.lua:1041: bad argument #1 to 'insert' (table expected, got nil)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: Nope
Have you looked through the Closed Topics?: Yes, found a similar issue but it did not fix mine. 
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: Nope
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: Nope
Are you using ExtendedMode?: Nope
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
This is a problem with esx_menus not my script.
