### ISSUE TITLE
Vehicle is not handed over

### ISSUE THREAD

**Issue by PremadeTV** [HumanTree92/esx_advancedvehicleshop#39]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  yes only to true
Have you looked through the Closed Topics?:  yes
Have you looked through the Wiki?:  No
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): V1 Final
Are you using Essentialmode?: yes
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: linux

Hello
when i buy a vehicle, the money is taken from me but i don't get the vehicle!
no new vehicle is shown in the database

Please help

**Comment by HumanTree92** [comment]
Can you provide an image or images of what you edited. Also i wouldn't recommend using Essentialmode.

**Comment by PremadeTV** [comment]
only activated the mechanic and the aircraft shop!
https://prnt.sc/vomb15
and as a video
https://streamable.com/fb9rs9

**Comment by HumanTree92** [comment]
Are there any errors at all. Check the client side logs & server side logs.

**Comment by PremadeTV** [comment]
found the error. I forgot to enter the category in the database owned_vehicles.
Now the only problem I have is that bought vehicles are in the garage immediately and do not spawn after buying them.

**Comment by HumanTree92** [comment]
The problem with not being put in your vehicle when you purchase it is on your end.
