### ISSUE TITLE
shops when buying vehicles

### ISSUE THREAD

**Issue by Blockbuster-bit** [HumanTree92/esx_advancedvehicleshop#4]
Hi there. if you want to buy a vehicle at the shops no matter because the car doesn't spawn at the dealer what could that be, please help quickly or edit quickly
Sorry for my english

**Comment by Blockbuster-bit** [comment]
Hi there. if you want to buy a vehicle and no matter what in the shop because the car does not spawn at the dealer what could that be, please help quickly or please edit quickly
Sorry for my english

**Comment by Blockbuster-bit** [comment]
I have exactly this problem as I did 6 days ago


Hello, When I try to resell a car bought at the vehicle/car shop nothing pops up,
I have found an issue where with every other sell point an error pops up in the F8 console and that also doesn't pop up, so I suspect it doesn't check for a vehicle

This is a picture of the console error I get when driving on top of other selling points without the right vehicle
(If I try to drive over the right selling point with a car, nothing pops up)

image

Thank you!
Kind regards, Pascal

**Comment by HumanTree92** [comment]
Currently right now since i am still setting up my test server without Images or Error info i can't do anything.

**Comment by Blockbuster-bit** [comment]
If you have time and feel like you could fix it please would be happy Thanks in advance

mfg P.B

**Comment by HumanTree92** [comment]
This should be fixed. I have fully tested this and everything works.
