### ISSUE TITLE
Cars not spawning but showing up in garage.

### ISSUE THREAD

**Issue by bizzlebug** [HumanTree92/esx_advancedvehicleshop#45]
**Describe the Bug | A Clear & Concise Description of Bug**
![image](https://user-images.githubusercontent.com/77012434/103707458-8fc2b600-4fa6-11eb-9f71-36d036686395.png)

When I attempted to purchase I get the following error inside the console, I checked the DB and all cars purchased are there but never spawned, I can't retrieve them from the garage as it says that the car isn't here.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.1
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: N/A
Are you using OneSync?: No
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Are you using es_extended V1.2 or es_extended V1 Final

**Comment by bizzlebug** [comment]
The manifest says v1.1.0

**Comment by HumanTree92** [comment]
Try using ESX V1 Final. You can find a link in the readme
