### ISSUE TITLE
Error "attempt to call a nil value (field 'ShowNotification')"

### ISSUE THREAD

**Issue by Christian21lp** [HumanTree92/esx_advancedvehicleshop#46]
**Describe the Bug | A Clear & Concise Description of Bug**

I want to Buy a Policecar in the Shop and when i press "E" this Error came.
SCRIPT ERROR: @esx_advancedvehicleshop/server/main.lua:371: attempt to call a nil value (field 'ShowNotification')
> ref (@esx_advancedvehicleshop/server/main.lua:371)
>  (@mysql-async/mysql-async.js:15543)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): es_extended 1.1
Are you using Essentialmode?: No
Are you using ExtendedMode?: Yes
Are you using OneSync?: No
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Try updating to ESX V1 Final

**Comment by Christian21lp** [comment]
I have update to Version ESX V1 Final and its the same Error

**Comment by HumanTree92** [comment]
So are you using ESX V1 Final or are you using Extendedmode. You can't use both at the same time.

**Comment by HumanTree92** [comment]
You could also just go into the server file & put a -- in front of the stuff on line 371
