### ISSUE TITLE
attempt to index a nil value (field 'ShopInsideCar')

### ISSUE THREAD

**Issue by leonard11255** [HumanTree92/esx_advancedvehicleshop#49]
**Describe the Bug | A Clear & Concise Description of Bug**
When entering a shop my character disappears and I get this error code:
![20210124213525_1](https://user-images.githubusercontent.com/77940862/105644624-be8dc700-5e96-11eb-92bf-e13b0504aec6.jpg)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: Yes
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.1.0 modified
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: No
Linux or Windows?: Windows

**Comment by leonard11255** [comment]
I modified the file correctly but I don't even have ShopInsideCar as a config anywhere in Config.lua let alone in the client.lua. If you want I can upload the modified file.

**Comment by HumanTree92** [comment]
I don't provide support if you modify the files incorrectly. You best bet is to read the error and go to the line where the problem is and fix it. If you don't know how to fix it don't modify the script.
