### ISSUE TITLE
Playermanagment

### ISSUE THREAD

**Issue by BaemLikeFanta** [HumanTree92/esx_advancedvehicleshop#50]
**Describe the Bug | A Clear & Concise Description of Bug**
Dont't know exactly if this is a bug but you said it works exactly like esx_vehicleshop

I can't finde a way to set player management. 

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: 
No
Have you looked through the Closed Topics?: 
Yes
Have you looked through the Wiki?: 
No where is it
Are you using a Pre-Installed ESX? If Yes who?: 
Plumesx but there is nothing original plume now
Are you using es_extended? If Yes what Version? (Example: 1.2): 
1.2
Are you using Essentialmode?: 
Need it for esx_jobs but it doesn't do anything else
Are you using ExtendedMode?: 
Think no not 100% sure now
Are you using OneSync?: 
No
Linux or Windows?: 
Windows

**Comment by HumanTree92** [comment]
This is everything like esx_vehicleshop but doesn't do player management. It will in the future have the ability for players to sell vehicles to other players. But currently not right now
