### ISSUE TITLE
InsideShop and OutsideShop Different Color/Livery

### ISSUE THREAD

**Issue by gerung** [HumanTree92/esx_advancedvehicleshop#51]
When the vehicles spawned the livery or color different as InsideShop, so if the police buy vehicles on "Division" and choose police livery but the livery is different when the vehicle is spawned, i get ambulance livery and not police livery even though policejob?

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: **No** 
Have you looked through the Closed Topics?: **No**
Have you looked through the Wiki?: **No**
Are you using a Pre-Installed ESX? If Yes who?: **No** 
Are you using es_extended? If Yes what Version? (Example: 1.2): **No** 
Are you using Essentialmode?: **No**
Are you using ExtendedMode?: **Yes**
Are you using OneSync?: **Yes**
Linux or Windows?: **Linux / Ubuntu**

**Comment by HumanTree92** [comment]
This isn't an issue or something that can be solved. U should implement a way for police and ambulance to change their liveries via vMenu or lscustoms.
