### ISSUE TITLE
No markers or blips

### ISSUE THREAD

**Issue by deputydavis** [HumanTree92/esx_advancedvehicleshop#52]
**Describe the Bug | A Clear & Concise Description of Bug**
I have no markers or blips for the vehicle shop. The only changes I have made were to make esx_advancedvehicleshop work with esx_policejob and esx_ambulancejob - Followed directions on main page. The funny thing is, the police job works. I can purchase the vehicles, and store them. Any help is greatly appreciated. Thanks!

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No - Fresh copy installed
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: No - Unable to locate
Are you using a Pre-Installed ESX? If Yes who?: Yes - PlumeESX
Are you using es_extended? If Yes what Version? (Example: 1.2): Yes - Plume doesn't specify what version is used.
Are you using Essentialmode?: No
Are you using ExtendedMode?: Yes
Are you using OneSync?: No
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Make sure you edit the config.lua. By default everything is turned off. Make sure you follow the Readme and have everything that is required. Make sure you remove esx_vehicleshop. Not sure how PlumeESX has it setup but you will need to remove esx_vehicleshop from everything. The guide link is found on the readme btw.

**Comment by deputydavis** [comment]
That was the issue, and I have fixed that. Now I have general question, is there a way to incorporate police vehicles into the private garages? 

You buy the police vehicle, store it in the garage and have to go back to the station to get the vehicle. We are using esx_properties and have private garages turned on but it only stores civ vehicles, and you cannot store police vehicles. 

Thanks for your time and help.

**Comment by HumanTree92** [comment]
I can implement a feature like this in the next update.

**Comment by HumanTree92** [comment]
I looked into doing this but currently there is no way without rewriting the entire Police & Ambulance Garage portion as the Cars & Helis are in the same menu. And the other option would be to add a spawner2 & heading2 for each private garage which would take way to long to do.
