### ISSUE TITLE
Newly bought cars go straight to impound

### ISSUE THREAD

**Issue by BrennanG0526** [HumanTree92/esx_advancedvehicleshop#54]
**Describe the Bug | A Clear & Concise Description of Bug**
Everytime I buy a vehicle, it puts it instantly into the impound and I have to go pay the $300 to retrieve it. I have looked through the configs, server, and client files but could not find anything pertaining to this specific issue.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): es_extended 1Final
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Post image of ur owned_vehicles  structure.

**Comment by BrennanG0526** [comment]
![image](https://user-images.githubusercontent.com/36135698/114297414-24d9bd00-9a76-11eb-8a87-4606c9d2594f.png)

**Comment by BrennanG0526** [comment]
Is that what you wanted?

**Comment by BrennanG0526** [comment]
oh structure, sorry hold on

**Comment by BrennanG0526** [comment]
![image](https://user-images.githubusercontent.com/36135698/114297442-4b97f380-9a76-11eb-95e5-981921d2c3f4.png)

**Comment by HumanTree92** [comment]
Any errors in the F8 console or the server console when purchasing the vehicle.

**Comment by BrennanG0526** [comment]
I have one about not being able to show a notification in the server/main.lua file on line 828. But I commented out that line just to see if there would be anything else and there wasn't.

**Comment by HumanTree92** [comment]
If your having that issue then you didn't setup ESX correctly. 

Are you using EssentialMode or es_extended V1 Final or ExtendedMode?
Have you tried Commenting that line out & then restarting the Script and purchasing a vehicle again.

Normally if your having issues with showing a Notification the reason is your not using es_extended V1 Final located here https://github.com/esx-framework/es_extended/tree/v1-final

**Comment by BrennanG0526** [comment]
Okay thanks. I thought I had everything installed correctly, odds are I don’t lol. I’ll take a look at it tomorrow (I need to stop staying up until 4am). Thanks for your fast responses by the way :)

**Comment by BrennanG0526** [comment]
And I also, yeah I restarted the server after commenting out those lines and got no more errors. But still no luck actually spawning the vehicle after buying it.

**Comment by ElectriziaDev** [comment]
![image](https://user-images.githubusercontent.com/88282619/129202440-2d5d4604-ebf7-4612-a4e5-948607bb520f.png)
Hello ! I have the same error but I waited 15 minutes. You should know that in the db that you put with, the primary keys are on the names and models, but this is not possible. So I put them on the ids. Can it be that? Thank you :)
