### ISSUE TITLE
Menu close automatically

### ISSUE THREAD

**Issue by ShadowOfVoid** [HumanTree92/esx_advancedvehicleshop#55]
**Describe the Bug | A Clear & Concise Description of Bug**

Well totally randomly the menu just closes without any error that will cause the player hang and the player have to leave the server and rejoin in order to play again . i really busted my ass to figure it out why it will just close it self but no luck ! if i move between cars or boats etc too fast in the menu the issue will be worse most of the time and the menu will just close and you will hang in the vehicle . + i even use the latest version

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: No ( cause there is no wiki )
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): v1.2.0
Are you using Essentialmode?:  No
Are you using ExtendedMode?: No
Are you using OneSync?: Yes infinity
Linux or Windows?: Windows

**Comment by ShadowOfVoid** [comment]
well , it seems like i had to cry more and after couple of month crying and crying here then i finally figured it out why ! it was another code in another resource that would close the menu :/ heh . anyway sry to bother , and thanks for the great res

**Comment by alartre** [comment]
> well , it seems like i had to cry more and after couple of month crying and crying here then i finally figured it out why ! it was another code in another resource that would close the menu :/ heh . anyway sry to bother , and thanks for the great res

Can u explain whichresource is closing menu? I have same issue and i really don't know which source is doing that. Ty for inconvenience @ShadowOfVoid
