### ISSUE TITLE
Unable to buy any Boats and Trucks

### ISSUE THREAD

**Issue by dragon703** [HumanTree92/esx_advancedvehicleshop#56]
**Describe the Bug | A Clear & Concise Description of Bug**
I can see the blips for the Boat Shop and Truck Shop on the map but once on that area, I don't see any shop indicators to interact with and I cant open the shop menu as well.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: Yes
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
You have to change the location yourself. As in my server i have Paid interiors. Also make sure the Shop = true & not false

**Comment by dragon703** [comment]
I did try changing the vectors to change the location, but for some reason its not visible at all. The Shop under the config file is also set to true.

**Comment by HumanTree92** [comment]
This script works perfectly fine & we have 0 issues. Things i would try
A. Raising & Lowering the Z Value by 1.0
B. Make sure your not using esx_vehicleshop

**Comment by dragon703** [comment]
I did try moving the Z Axis for the Blip Markers but still couldn't see any markers. And I am definitely using esx_advancedvehicleshop only. I'll go through my other mods, maybe the issue is caused by something else. Thanks for the help.
