### ISSUE TITLE
READ

### ISSUE THREAD

**Issue by huzball** [HumanTree92/esx_advancedvehicleshop#57]
So this isn't a script issue, more like your prewritten text can be easily misinterpreted.

Where it says `Shop = ... & Blips =` you want those true if you want them shown & used. But the way you wrote it made it seem like false does the opposite of if you turn it true... 
You wrote out something so obvious that's why it threw me off.
`Shop = false, --true = Use Ambulance Shop | false = Does Opposite`
it made it seem like by default it is true and uses the shop & if you put it to false it does the opposite.
So far anyone that can't see the **BLIPS** & **SHOPS** make sure the config is set to **TRUE** not _false_

Haha unfortunate misunderstanding. But this is great ! Thank you so much!

**Comment by HumanTree92** [comment]
By Default i have everything set to false aka not being used. As i want players to edit the config.lua to their choosing.
For example i have in the ReadMe "Edit the config.lua before starting the script. By default everything is turned off."
