### ISSUE TITLE
Car dealership list disappears when switching to other cars

### ISSUE THREAD

**Issue by Maureks** [HumanTree92/esx_advancedvehicleshop#59]
**Describe the Bug | A Clear & Concise Description of Bug**
Hello, i've installed the resource, and its working fine , the only issue I have , is that , when trying to buy a vehicle from the Vehicle Shop , and trying to switch to see other cars , the list disappears as if you bought the car , and you get stuck inside the car unable to get out or do anything. Pressing Esc and F keys dont work. In the consoles, F8 , Live Console , TxAdmin , no errors seem to appear.
What can I do? or try , to resolve the issue of the disappearing list?

P.S - Sorry for bad english

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: Yes , PlumeEsx 05/2021
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2.0
Are you using Essentialmode?: No
Are you using ExtendedMode?: No
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Not sure if PlumeESX is using ESX V1 Final or ESX Legacy but i would try using ESX V1 Final. The Best way ATM to fix getting stuck in the dealership is to hit F8 & do /restart esx_advancedvehicleshop 

I have seen this problem before but its not a problem with this script. It normally comes down to something wrong with your base Script or Script load order.
