### ISSUE TITLE
esx_policejob - Not a bug or really even your problem... Just hoping for help for me and others.

### ISSUE THREAD

**Issue by balancedliferp** [HumanTree92/esx_advancedvehicleshop#6]
I am in LOVE with this script but would you know how to get this to work with esx_policejob? I REALLY want to use your script but it will not work as-is with esx_policejob. Would you have any idea on how to make them work together as esx_vehicleshop is a requirement for policejob. Edit: in the meantime I am going to try to run both and see how that works. :)

**Comment by HumanTree92** [comment]
You can edit esx_policejob client/vehicle.lua and do a search for esx_vehicleshop & change it to esx_advancedvehicleshop then edit fxmanifest.lua & remove the dependency for esx_vehicleshop

**Comment by balancedliferp** [comment]
You are amazing! Thank you for the quick reply!

**Comment by HumanTree92** [comment]
2311600e0702b2dba9b1341b44925688989ad583
