### ISSUE TITLE
SCRIPT ERROR: @esx_advancedvehicleshop/client/main.lua:1015: attempt to get length of a nil value (upvalue 'VehiclesC')

### ISSUE THREAD

**Issue by Lopottaja** [HumanTree92/esx_advancedvehicleshop#61]
When i walk into the shop circle, it shows the prompt to press E, but when i press it, nothing happens and the prompt just disapears and the error "SCRIPT ERROR: @esx_advancedvehicleshop/client/main.lua:1015: attempt to get length of a nil value (upvalue 'VehiclesC')" shows up in the console.

Im new to making fivem servers, so i dont know hoe to fix this

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: Plume
Are you using es_extended? If Yes what Version? (Example: 1.2): yes, 1.2
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: no
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Line 1015??? This is what is line it is https://github.com/HumanTree92/esx_advancedvehicleshop/blob/master/client/main.lua#L1015 unless you are running and outdated download.

**Comment by Lopottaja** [comment]
Ok, i got i working just by redoing the sql database, cuz i deleted it by accident. Now shop works fine.
