### ISSUE TITLE
No textures / No blips

### ISSUE THREAD

**Issue by maltesserver** [HumanTree92/esx_advancedvehicleshop#63]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): yes, 2.0.1
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: no
Linux or Windows?: linux

Hi,

I Installed Advancedvehicleshop to my server. i added the cars to the database and restarded my server. however, i didnt see any blips for the car dealer or any way of opening it. I then installed the Bob74 IPL files and could now enter the car dealer. however i still dont see a blip 

![grafik](https://user-images.githubusercontent.com/56297305/124341938-a5104a00-dbaf-11eb-85da-745edeb35889.png)

Can you help me? I do not know anymore what I did wrong

**Comment by maltesserver** [comment]
edit: fixed by dumping this script and using a different one.

**Comment by HumanTree92** [comment]
Not the scripts fault. Its the users fault. If you looked through the closed issues you would have seen how to fix this problem.
