### ISSUE TITLE
if i put mijn vehcile in to the car shop i get a error

### ISSUE THREAD

**Issue by maudutch** [HumanTree92/esx_advancedvehicleshop#64]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.0.12
Are you using Essentialmode?: essentialmode
Are you using ExtendedMode?: dont know
Are you using OneSync?: dont know
Linux or Windows?: windows
![image](https://user-images.githubusercontent.com/87568434/126035124-7c3982a5-b2c5-4222-b5f8-6a6e5ff2ec42.png)
![image](https://user-images.githubusercontent.com/87568434/126035143-f46fe541-08df-4868-9ecd-b6b365755bce.png)

**Comment by HumanTree92** [comment]
Please follow the readme. Also your grammar is terrible.
