### ISSUE TITLE
Going invisible, can't solve without logging off then back in.

### ISSUE THREAD

**Issue by Shinotama** [HumanTree92/esx_advancedvehicleshop#65]
**Describe the Bug | A Clear & Concise Description of Bug**
As the title says, I am going invisible when I purchase a car, it's literally happening in any of the garages, the menu works fine etc, when you buy a car you straight up end up invisible, you can leave your car but then cannot move almost like your bound to that spot, and again, you cannot move or do anything..

I did see that someone else had this issue also but I have done the same as them, it's not solved anything.

The version of esx I had already changed the dependencies of ambulance job and police job to esx_advancedvehicleshop in the fxmanifest.lua

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: Plume
Are you using es_extended? If Yes what Version? (Example: 1.2): ESX_Legacy 
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
This issue would most likely be a Plume issue. And as far as i know Plume isn't using ESX Legacy. I have now updated all my scripts to support ESX Legacy.
