### ISSUE TITLE
Incorrect table definition (SQL)

### ISSUE THREAD

**Issue by NightBlue031** [HumanTree92/esx_advancedvehicleshop#67]
**Describe the Bug | A Clear & Concise Description of Bug**

Everything is described in a picture.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): No
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: Yes
Are you using OneSync?: No
Linux or Windows?: Windows
![Desktop Screenshot 2021 09 03 - 16 42 14 36](https://user-images.githubusercontent.com/90053544/132024540-f4b3f641-7fce-4330-bdcd-7fcb463e5adc.png)

**Comment by HumanTree92** [comment]
I would try the latest update. Also make sure you are using ESX Legacy.
