### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by Pedrozxz** [HumanTree92/esx_advancedvehicleshop#68]
**Describe the Bug | A Clear & Concise Description of Bug**

Hi, I don't know why but I have this error on the console and in the game when I try to access the menu to buy anything I don't see anything, I don't understand how I get this to work I've reviewed the steps several times and nothing .

[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_division_categories` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_division_categories' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_aircraft_categories` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_aircraft_categories' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_boat_categories` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_boat_categories' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_car_categories` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_car_categories' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_truck_categories` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_truck_categories' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_divisions` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_divisions' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_aircrafts` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_aircrafts' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_boats` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_boats' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_cars` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_cars' doesn't exist
[  script:mysql-async] [MariaDB:10.4.21-MariaDB] [ERROR] [esx_advancedvehicleshop] An error happens for query "SELECT * FROM `vs_trucks` : []": ER_NO_SUCH_TABLE: Table 'plumeesxlegacy_3393a1.vs_trucks' doesn't exist

**Questions**
Have you made changes to anything besides the `config.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: I have but I don't know which one I'm new to fivem.
Are you using ESX Legacy?: Yes
Are you using OneSync?: No
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Maybe you should ask Plume why it can't find the tables. So long as you have uploaded the SQL it would find it. My guess is Plume is the problem. In honesty Plume is dog crap. You should install each script by itself. The only All in One pack that is decent is RibSoSay. Plume just grabs the Master Version of Each and Every script. Which sometimes isn't a good thing.

But make sure you have upload the SQL for this script or any scripts you plan on using into the correct Database. 

I don't use plume nor would i ever recommend it. Its better to install each script by itself instead of an All in One Download as most All in One Downloads install scripts that you don't need or won't use.
