### ISSUE TITLE
Bug in server

### ISSUE THREAD

**Issue by Dokman** [HumanTree92/esx_advancedvehicleshop#69]
**Describe the Bug | A Clear & Concise Description of Bug**
I cannot load the script
![image](https://user-images.githubusercontent.com/2290904/133147957-58cd1c5b-5c91-4340-b0a3-d72a306af69a.png)
![image](https://user-images.githubusercontent.com/2290904/133148630-f15c64b3-e983-4898-a287-2cfa036dead7.png)

**Questions**
Have you made changes to anything besides the `config.lua`?:  activated private cars
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: PlumeESX
Are you using ESX Legacy?:  Yes
Are you using OneSync?:  No
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Does your es_extended have an imports.lua file?

**Comment by Dokman** [comment]
It's a normal PlumeESX Server not anything else

**Comment by HumanTree92** [comment]
Well there should be an es_extended file and if it doesn't have an imports.lua file inside you will have to use the Release Version.

**Comment by Dokman** [comment]
it has it, what i can do?

**Comment by Bitrate2001** [comment]
I've got the same problem, what can i do?
I checked and yes, es_extended have an imports.lua file
![dump](https://user-images.githubusercontent.com/91150658/134219326-fbedfd79-1fdb-4040-b251-7c34732c6d67.jpg)

**Comment by HumanTree92** [comment]
My guess is its the DLC Vehicles. I forgot to remove them and add them in their own SQL. That is my only guess.

**Comment by Bitrate2001** [comment]
How can I do it, sorry, but I'm a newbie

**Comment by HumanTree92** [comment]
Go into the SQL and remove all DLC Vehicles

**Comment by Bitrate2001** [comment]
I had already removed all the cars from vs_cars, because I have to put more, but it still doesn't work

**Comment by harderxbx** [comment]
I have the same problem.
I removed all DLC vehicles from the database.
I can't find a solution for this on the internet. The only strange thing is that it worked 2 days ago. Then I set up my fivem ESX server again (Unbuntu Linux) and then it didn't work anymore. I have implemented all the suggested solutions that are in here but without success.

**Comment by HumanTree92** [comment]
Make sure you are using the es_extended that has the imports.lua file.

**Comment by harderxbx** [comment]
The file exists. But what does this file do?

**Comment by harderxbx** [comment]
I have. Delete the Folder "esx_vehicleshop" from resources folder. something doesn't seem to be understood. But it works

**Comment by HumanTree92** [comment]
Ight. Well i have a major update coming to my esx_advancedvehicleshop and esx_advancedgarage that will make editing easier. With less code as well. I will be releasing the updates sometime next week after i fully test everything.
