### ISSUE TITLE
Car Dealer Bug

### ISSUE THREAD

**Issue by phpadmin1** [HumanTree92/esx_advancedvehicleshop#7]
You can open the menu car dealer even if you don't have a license and the problem without license when you go down or if you want to choose another cars you'll get stuck after that.

If you have driving license when you open the car menu shop 
the first car remains if you choose another cars. 
the car spawn

Please fix this thank you .more power

**Comment by HumanTree92** [comment]
This should be fixed. I have fully tested this and everything works.
