### ISSUE TITLE
SQL not importing

### ISSUE THREAD

**Issue by acidbandicoot** [HumanTree92/esx_advancedvehicleshop#70]
INSERT INTO `owned_vehicles` (	`owner` varchar(40) NOT NULL,	`plate` varchar(12) NOT NULL,	`vehicle` longtext NOT NULL,	`type` VARCHAR(20) NOT NULL DEFAULT 'car',	`job` VARCHAR(20) NOT NULL DEFAULT 'civ',	`category` VARCHAR(50) DEFAULT NULL,	`name` varchar(60) NOT NULL DEFAULT 'Unknown',	`fuel` int(11) NOT NULL DEFAULT '100',	`stored` TINYINT(1) NOT NULL DEFAULT '0',	`image` longtext DEFAULT NULL,	PRIMARY KEY (`plate`));

not sure how to go from here

**Questions**
Have you made changes to anything besides the `config.lua`?: y
Have you looked through the Closed Topics?: y
Have you looked through the Wiki?: y
Are you using a Pre-Installed ESX? If Yes who?: not sure
Are you using ESX Legacy?: y
Are you using OneSync?: y
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Try downloading the new sql and try it again.
