### ISSUE TITLE
Not able to Import SQL to Database Need HElp

### ISSUE THREAD

**Issue by Assault-Tamizha** [HumanTree92/esx_advancedvehicleshop#71]
**Describe the Bug | A Clear & Concise Description of Bug**
Not able to Import the SQL to the Database Shows an error that Incorrect Table Definition There can be only one auto column and it should be defined as a key

**Questions**
Have you made changes to anything besides the `config.lua`?: Just the True and false statements
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: ZAP
Are you using ESX Legacy?:  Yes
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Just updated to fix this.
