### ISSUE TITLE
Shops inside building and no showing up blibs

### ISSUE THREAD

**Issue by Erani0** [HumanTree92/esx_advancedvehicleshop#72]
**Describe the Bug | A Clear & Concise Description of Bug**
I have edit the config for activate blibs and activate the shops.

Vip, Truck, boat all shops are inside building with no access.
and blibs not showing up  

**Questions**
Have you made changes to anything besides the `config.lua`?: yes 
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: 
Are you using a Pre-Installed ESX? If Yes who?: yes
Are you using ESX Legacy?: yes
Are you using OneSync?: yes
Linux or Windows?: linux

**Comment by HumanTree92** [comment]
You will need to edit those locations. You can do so with vMenu by showing coordinates.
