### ISSUE TITLE
Advanced Car Garagew

### ISSUE THREAD

**Issue by madalex24** [HumanTree92/esx_advancedvehicleshop#75]
Ive purchased a car, it has registered but when i go and park it, it says there is no car available at the place i just parked it. What do i have to do to find it?

**Questions**
Have you made changes to anything besides the `config.lua`?: 
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using ESX Legacy?: yes
Are you using OneSync?: 
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Post an image of your owned_vehicles structure and database

**Comment by Ardentrayne** [comment]
This is the one set up currently under my username:
![image](https://user-images.githubusercontent.com/91555598/135703635-5b83224f-55d5-4a23-a85a-abafc3b763a5.png)

**Comment by HumanTree92** [comment]
?

**Comment by madalex24** [comment]
Sorry for the late reply,

I hope this works. I saw that there was a fix but it got deleted.

Alex

**Comment by HumanTree92** [comment]
I have no clue what you are talking about.

**Comment by madalex24** [comment]
Hi, You told me to send my database data and structure so I did as I was using the above. I also noticed that was a fix for it but it was deleted. Alex Sent from Mail for Windows From: William Plunkett JrSent: 02 October 2021 19:26To: HumanTree92/esx_advancedvehicleshopCc: madalex24; AuthorSubject: Re: [HumanTree92/esx_advancedvehicleshop] Advanced Car Garagew (#75) I have no clue what you are talking about.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HumanTree92** [comment]
Ok honestly i don't understand any messages you are sending. So im going to close the issue till you can post an IMAGE of your owned_vehicles STRUCTURE and DATABASE

**Comment by madalex24** [comment]
I sent the images in attachments. Sent from Mail for Windows From: William Plunkett JrSent: 03 October 2021 04:39To: HumanTree92/esx_advancedvehicleshopCc: madalex24; AuthorSubject: Re: [HumanTree92/esx_advancedvehicleshop] Advanced Car Garagew (#75) Ok honestly i don't understand any messages you are sending. So im going to close the issue till you can post an IMAGE of your owned_vehicles STRUCTURE and DATABASE—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HumanTree92** [comment]
Nope no images. Try not using your Email to reply. Use github.com to reply. As what you are trying to do is coming back as a big mess.
