### ISSUE TITLE
mysql error for owning bought vehicles

### ISSUE THREAD

**Issue by Ardentrayne** [HumanTree92/esx_advancedvehicleshop#76]
Hi I've been getting an error basically that says: [esx_advancedvehicleshop] An error happens for query "INSERT INTO owned_vehicles. I've tried alot of solutions for this but still can't get it to work, this happens basically when i buy the vehicle, in game it says I own it but I get this error. This also stops me from being able to pull it out from my garage once i store it because its technically not mine due to the error. Any advice would be great~ 

also here's an image of the full thing (hopefully it shows):
![image](https://user-images.githubusercontent.com/91555598/135703364-9314f9de-4a86-4970-99ad-6d4c187fc309.png)

**Questions**
Have you made changes to anything besides the `config.lua`?: 
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: 
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using ESX Legacy?: 
Are you using OneSync?: 
Linux or Windows?:

**Comment by HumanTree92** [comment]
Post an image of your owned_vehicles structure

**Comment by Ardentrayne** [comment]
This should be the one:
![image](https://user-images.githubusercontent.com/91555598/135749658-319f9fb7-6ef5-4674-ad59-d5b4a80d274d.png)

**Comment by HumanTree92** [comment]
Judging from the screenshot it looks like your using the Release Version. But just as a heads up the Job Column shouldn't be NULL as you can see here https://github.com/HumanTree92/esx_advancedvehicleshop/blob/V1/esx_advancedvehicleshop.sql#L13

**Comment by Ardentrayne** [comment]
Okay that makes sense but also How would I go about changing that exactly?

**Comment by HumanTree92** [comment]
Delete ur current owned_vehicles and upload mine. Or click the change button in structure

**Comment by Ardentrayne** [comment]
And to upload I'd just basically be putting in the SQL right? when i go to change the structure i see a few things does it matter which one of these I choose?
![image](https://user-images.githubusercontent.com/91555598/136107781-211398fd-ce64-427c-8e70-0017cad20ee5.png)

**Comment by Ardentrayne** [comment]
I've tried to reinput the SQL as well as create my own table and that didn't end up working I got the same error. I've attached an image of the structure:
![image](https://user-images.githubusercontent.com/91555598/136122942-3ca14172-1190-4157-8c04-95850a403683.png)

**Comment by Ardentrayne** [comment]
Okay so update I got it to work, I understood what you said and tried it that way with editing the sql to what was missing which was basically the creation table! Thank you for your help!
