### ISSUE TITLE
Char of User too long 

### ISSUE THREAD

**Issue by Jhu2501** [HumanTree92/esx_advancedvehicleshop#79]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything besides the `config.lua`?: 
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: 
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using ESX Legacy?: 
Are you using OneSync?: 
Linux or Windows?: 

No I haven’t 
Yes I looked through them
Yes
Plume ESX
Yes I use ESX Legacy
What is onesync?
Windows

Hi, my problem is, that if I try to buy or give a car, I get an error message that the user Char is too long… if I edit the user char, the error message goes away but no car is in my garage

**Comment by Jhu2501** [comment]
[  script:mysql-async] [MariaDB:10.4.18-MariaDB-1:10.4.18+maria~buster-log] [ERROR] [esx_givevehicle] An error happens for query "INSERT INTO owned_vehicles (owner, plate, vehicle, stored, type) VALUES (?, ?, ?, ?, ?) : ["0a008d8abd49d5e06ef9edb88742af1e5e30c20b","AIA 744","{\"modWindows\":-1,\"modSeats\":-1,\"modFrontWheels\":-1,\"modEngineBlock\":-1,\"engineHealth\":1000.0,\"modTrimB\":-1,\"extras\":{\"1\":false,\"2\":false},\"modShifterLeavers\":-1,\"wheelColor\":122,\"modTrunk\":-1,\"modFrontBumper\":-1,\"modAPlate\":-1,\"modSmokeEnabled\":false,\"modOrnaments\":-1,\"modBackWheels\":-1,\"modArmor\":-1,\"modSpoilers\":-1,\"modHydrolic\":-1,\"modHorns\":-1,\"dirtLevel\":4.0,\"modGrille\":-1,\"neonEnabled\":[false,false,false,false],\"modAerials\":-1,\"modSpeakers\":-1,\"modTransmission\":-1,\"pearlescentColor\":43,\"modTank\":-1,\"modSteeringWheel\":-1,\"modDial\":-1,\"plateIndex\":0,\"modRoof\":-1,\"tyreSmokeColor\":[255,255,255],\"bodyHealth\":1500.0,\"modRightFender\":-1,\"modTurbo\":false,\"xenonColor\":255,\"modHood\":-1,\"modPlateHolder\":-1,\"modSideSkirt\":-1,\"modArchCover\":-1,\"modVanityPlate\":-1,\"modSuspension\":-1,\"modExhaust\":-1,\"color1\":43,\"modRearBumper\":-1,\"wheels\":7,\"modEngine\":-1,\"modBrakes\":-1,\"modFrame\":-1,\"neonColor\":[255,0,255],\"modXenon\":false,\"color2\":43,\"modFender\":-1,\"modTrimA\":-1,\"plate\":\"AIA 744\",\"modAirFilter\":-1,\"model\":629640447,\"tankHealth\":1000.0,\"windowTint\":-1,\"modDashboard\":-1,\"fuelLevel\":65.0,\"modStruts\":-1,\"modLivery\":10,\"modDoorSpeaker\":-1}",1,"car"]": ER_DATA_TOO_LONG: Data too long for column 'owner' at row 1

**Comment by HumanTree92** [comment]
Not an issue with this script at all. Check with esx_givevehicle
