### ISSUE TITLE
It Sais you own the car but you don't.

### ISSUE THREAD

**Issue by rayyanallaf** [HumanTree92/esx_advancedvehicleshop#8]
So I'm having a problem where I can buy the car and it even tells me that this registered license belongs to you know. I even check owned_vehicles in the database and the car shows up their as well with all the correct info. When I go to sell or store my car it doesn't let me. it sais i don't own it. I'm using esx_advancedgarage. Can you possibly help with this?

**Comment by HumanTree92** [comment]
This should be fixed. I have fully tested this and everything works.
