### ISSUE TITLE
 bad argument to insert(table expected, got nil)

### ISSUE THREAD

**Issue by Luke20201** [HumanTree92/esx_advancedvehicleshop#80]
**Describe the Bug | A Clear & Concise Description of Bug**
When pressing E at the Vehicle shop, it throw's an error for client/main.lua:1303 bad argument to insert for a table is nil
The method is:
```
for i=1, #VehiclesC, 1 do
		if IsModelInCdimage(GetHashKey(VehiclesC[i].model)) then
			table.insert(vehiclesByCategory[VehiclesC[i].category], VehiclesC[i])
		else
			print(('[esx_advancedvehicleshop] [^3ERROR^7] Boat "%s" does not exist'):format(VehiclesC[i].model))
		end
	end
```

**Questions**
Have you made changes to anything besides the `config.lua`?:  Yes, I remove the Dependency for DMV School.
Have you looked through the Closed Topics?:  Yes
Have you looked through the Wiki?: No
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using ESX Legacy?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Linux

**Comment by HumanTree92** [comment]
I've got an update coming out this week that will fix most issues so long as you are using ESX Legacy. However with your issue you have made a mistake somewhere. I don't give support for people who edit anything outside the config.lua. B/c i have no way of testing the edited versions to figure out the problem. But you can easily remove the dependency for DMV School by setting the  Licenses to false in the config.lua

**Comment by Luke20201** [comment]
> 

I reverted back to the orignal files, with only edit's being made to the config, which causes this error in the console:
```Error loading script server/main.lua in resource esx_advancedvehicleshop: @esx_advancedvehicleshop/server/main.lua:92: attempt to index a nil value (global 'ESX')
[script:esx_advancedv] stack traceback:
[script:esx_advancedv] 	@esx_advancedvehicleshop/server/main.lua:92: in main chunk
```
as well as
```@esx_advancedvehicleshop/server/main.lua:48: attempt to call a nil value (global 'mysqlCar')```

**Comment by HumanTree92** [comment]
I would try using the latest update by downloading the master. Also make sure your es_extended files look very similar to this https://github.com/esx-framework/esx-legacy/tree/main/%5Besx%5D/es_extended if you don't have an imports.lua file then your not using the latest ESX Legacy.

**Comment by Luke20201** [comment]
> 

Could be something to do with the fact I modified a lot of the framework, however imports.lua is present and untouched, so I'm not sure how that could cause ESX to be nil.

**Comment by Luke20201** [comment]
Hey, so I tried fixing this again by doing a hard reinstall, and it still throw's the same error message. All I edited was the config.

**Comment by HumanTree92** [comment]
> Hey, so I tried fixing this again by doing a hard reinstall, and it still throw's the same error message. All I edited was the config.

Which is exactly what error code. As the code has been changed i just need the new line.
