### ISSUE TITLE
police,ambulance and lscustom

### ISSUE THREAD

**Issue by tonibanks** [HumanTree92/esx_advancedvehicleshop#9]
Can't start the resources..i tried to change the dependencies to esx_advancedvehicleshop can't buy the vehicle from police and ambulance & lscustom as well

**Comment by Mobius1** [comment]
You need to remove the dependency from `__resource.lua` / `fxmanifest.lua` and replace all instances of `esx_vehicleshop` with `esx_advancedvehicleshop` in the packages `*.lua` files. Worked for me.
